name: Publish Release

on:  
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gf-frame
    environment:
      name: build
      url: ${{ steps.create_release.outputs.html_url }}
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Create Tag
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_ACCESS }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: true
          prerelease: false

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Publish release
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              github.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: process.env.release_id,
                draft: false
              })

